### ISSUE TITLE
Customize the output of POLL_START_DATE and  POLL_END_DATE

### ISSUE THREAD

**Issue by errotu** [lesterchan/wp-polls#157]
Hi! First of all: Thank you for this great plugin! 

Is there any possibility to customize the output of  %POLL_START_DATE% and %POLL_END_DATE%? Currently, it looks rather technical (quote from a German wordpress):

> 4. Dezember 2023 00000012 14:51 170169791402Mo, 04 Dez 2023 14:51:54 +0100

I'd like to trim it down to just Day. Month Year (e.g. "4. Dezember 2023") but did not find any option to do so.

Thanks a lot for your help!

**Comment by oleole39** [comment]
Hi, 

Check this code sample to understand how those dates are generated by the plugin by default: 
```php
$poll_start_date = mysql2date(sprintf(__('%s @ %s', 'wp-polls'), get_option('date_format'), get_option('time_format')), gmdate('Y-m-d H:i:s', $poll_question->pollq_timestamp));
```
So the output you get is likely to be related to [your site's default configuration regarding date and time format](https://wordpress.org/documentation/article/customize-date-and-time-format/).

If you need to keep your default site's settings as they are and would only like the plugin's date and time format to be modified, and if you don't mind writing PHP code, you can achieve that in a fairly easy way by adding 2 custom filtering callback functions to your theme's `functions.php` (together with their `add_filter()` call):

The first one would modify targeted values and be hooked to those filters for vote and result forms:
```
wp_polls_template_voteheader_variables
wp_polls_template_votefooter_variables
wp_polls_template_resultheader_variables
wp_polls_template_resultfooter_variables
```
The other one would have to search and replace the targeted value in the archive page markup before it gets printed by hooking to that filter:
```
wp_polls_archive
```

You will find the structure of the content you need to filter in the file [wp-polls.php](https://github.com/lesterchan/wp-polls/blob/master/wp-polls.php)

Best,
oleole39

**Comment by errotu** [comment]
Hi oleole39, thanks a lot for your detailed explanation, and I'm really sorry for the late reply.

Unfortunately, the plugin does not use my site's default configuration regarding date and time format (I think that would be the desired behavior, see below for my settings). So I guess it's a bug that the plugin ignores this setting?

![grafik](https://github.com/lesterchan/wp-polls/assets/12113437/22794169-d9a9-4feb-9ab1-7306b577dbdb)

**Comment by oleole39** [comment]
Hello,

> > 7\. Dezember 2023 00000012 14:51 170169791402Mo, 04 Dez 2023 14:51:54 +0100

Can you share the code you use to generate that string (i.e. where you include %POLL_START_DATE%` and `%POLL_END_DATE%`) ?

**Comment by errotu** [comment]
It's the following:

> <p>Umfrage vom %POLL_START_DATE%</p>

(from the "Individual Poll Footer", "Umfrage von" translates to "Poll from")

**Comment by oleole39** [comment]
So what is the full string displayed on the user side ? `Umfrage vom 7. Dezember 2023 00000012 14:51 170169791402Mo, 04 Dez 2023 14:51:54 +0100` ?

**Comment by oleole39** [comment]
> Also would you have made a custom translation of the plugin

I reproduced the issue by switching Wordpress to German locale and reinstalling WP-polls so that it comes with its own German locale. The issue lies in the plugin's German translation string for the code sample I indicated in my first message above (`%s @ %s`). This has been translated in German by `%s um %s Uhr`. However this is wrong because each of the letters in`umUhr` gets interpreted as [date format characters](https://www.php.net/manual/en/datetime.format.php) leading to the strange output string you noticed. I would recommend to come back to the orignal string instead, unless you have something more adequate in mind.
You will need to update those two files:
- `/wp-content/languages/plugins/wp-polls-de_DE.po`
- `/wp-content/languages/plugins/wp-polls-de_DE.mo`

You may want to do the modification [there](https://translate.wordpress.org/projects/wp-plugins/wp-polls/stable/de/default/?filters%5Bterm%5D=%25s+%40+%25s&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) so that you wouldn't need to do it manually at each plugin's upgrade. Bear in mind that this will impact all users of the plugin's German locale and it should not cover a very specific case.
Then you can generate .po/.mo files from that page (see the feature "Export" at the bottom of the page) and rename them accordingly so that they replace your existing WP-Polls translation files at `/wp-content/languages/plugins/`.

**Comment by errotu** [comment]
Thanks a lot for the detailed, excellent explanation and pointing me towards the solution! 

I fixed the bug [by escaping the characters](https://translate.wordpress.org/projects/wp-plugins/wp-polls/stable/de/default/?filters%5Bterm%5D=%s%20@%20%s&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc):

>  	%s \u\m %s \U\h\r

In my installation, I also had to update/export the wp-polls-de_DE.l10n.php file.
