### ISSUE TITLE
Adding soundcloud widget to poll

### ISSUE THREAD

**Issue by poonasor** [lesterchan/wp-polls#44]
Im trying to find where the information is stored for each poll, to add an option to insert a embedded soundcloud player for a client. 

Ive checked phpmyadmin in the database for the entries and it did not match the information from wordpress.

I have no problem editing the template but I need to know how I would be able to add a new column for the soundcloud embed.

Thank you very much.

**Comment by espellcaste** [comment]
I'm at a lost of the correlation between SoundCloud and wp-poll.. How could it be both used together? Could you elaborate on that?

**Comment by poonasor** [comment]
my client wants to have a poll system for audio files, to have an embed soundcloud widget on the wp-poll, my question is where the information is stored so i can add that soundcloud column into the database, but I've checked the database for wp-polls and it doesn't contain the new polls information.

**Comment by lesterchan** [comment]
Hi Ricky,

I saw your Github issue but I don't respond to modification help/request for the plugin because it is not within my support scope since my plugin is already provided for free.

Just a tip, there are two tables pollsa stores the answers and pollsq store the questions.

All the templates are stored in wp_options which is WP default options table.

Good luck.
