### ISSUE TITLE
It is not correctly managing the plural form for "votes" in poll results.

### ISSUE THREAD

**Issue by cablop** [lesterchan/wp-polls#51]
The plugin is not showing the singular form "vote" when showing results for only one vote.

Instead of saying *"(11%, 1 Vote)"* it says *"(11%, 1 Votes)"*.

The problem is in the `.' %POLL_ANSWER_VOTES% '.__('Votes', 'wp-polls').` of the line:
```php
add_option('poll_template_resultbody', '<li>%POLL_ANSWER% <small>(%POLL_ANSWER_PERCENTAGE%%'.__(',', 'wp-polls').' %POLL_ANSWER_VOTES% '.__('Votes', 'wp-polls').')</small><div class="pollbar" style="width: %POLL_ANSWER_IMAGEWIDTH%%;" title="%POLL_ANSWER_TEXT% (%POLL_ANSWER_PERCENTAGE%% | %POLL_ANSWER_VOTES% '.__('Votes', 'wp-polls').')"></div></li>');
```
of the file *wp-polls.php*.

I wanted to fix it replacing the `__()` function with the `_n()` function, but your code does not process the variables there, so i ignore how to properly fix the issue there.

Could to rephrase *"(11%, 1 Votes)"* this way *"(11%, Votes: 1)"* be a workaround?

*Reference:*
[_n() function](https://codex.wordpress.org/Function_Reference/_n), function to provide alternate translation texts based on the singular|plural value used in the text.

**Comment by lesterchan** [comment]
Because the poll uses template system, it will not take into consideration plural and singular. It is just too much extra work for something you will not get to see 90% of the time.

The code you pasted doesn't matter because it is still template base and that code just pre-populate it. You can always change the way it is re-presented in WP-Admin -> Polls -> Poll Templates.
