### ISSUE TITLE
Comparing boolean with integer

### ISSUE THREAD

**Issue by jeroneemou** [lesterchan/wp-polls#92]
Hi there,

https://github.com/lesterchan/wp-polls/blob/master/polls-manager.php#L34
you're comparing integer with boolean on this line and date of start cannot be edited?. Probably should be fixed. 

Thanks

**Comment by elkirkmo** [comment]
`false == 0` in php. I am unable to recreate the start date not being editable without removing the [ternary operator fix](https://github.com/lesterchan/wp-polls/commit/ca6eb4d570009a542d5ec2a526b187223693ee78#diff-ee45ba87466a2730aa3570ac2d4e6f44). It's likely that the issue is due to your plugin not being updated to the latest version. I've submitted a pull request for the fix you suggested, but `false` likely isn't causing this issue.
